INSERT INTO user_rules (user_id, rule_type, operator, rule_value, target_label, enabled, priority)
VALUES
    (NULL, 'sender_domain', 'contains', 'steampowered.com', 'Security', TRUE, 280),
    (NULL, 'sender_domain', 'contains', 'nvidia.com', 'Security', TRUE, 270),
    (NULL, 'sender_domain', 'contains', 'id.apple.com', 'Security', TRUE, 270),
    (NULL, 'sender_domain', 'contains', 'hetzner.com', 'Security', TRUE, 260),
    (NULL, 'any', 'contains', 'security code', 'Security', TRUE, 260),
    (NULL, 'any', 'contains', 'new sign in', 'Security', TRUE, 250),
    (NULL, 'any', 'contains', 'new sign-in', 'Security', TRUE, 250),
    (NULL, 'any', 'contains', 'login link', 'Security', TRUE, 250),
    (NULL, 'any', 'contains', 'authenticator recovery', 'Security', TRUE, 250),
    (NULL, 'any', 'contains', 'account information updated', 'Security', TRUE, 245),
    (NULL, 'any', 'contains', 'access details', 'Security', TRUE, 240),
    (NULL, 'any', 'contains', 'authentication to your account', 'Security', TRUE, 240),

    (NULL, 'sender_domain', 'contains', 'permatabank.co.id', 'Transactions', TRUE, 250),
    (NULL, 'sender_domain', 'contains', 'customers.go-pay.co.id', 'Transactions', TRUE, 245),
    (NULL, 'any', 'contains', 'incoming transfer', 'Transactions', TRUE, 230),
    (NULL, 'any', 'contains', 'top up', 'Transactions', TRUE, 220),
    (NULL, 'any', 'contains', 'e-statement', 'Transactions', TRUE, 220),
    (NULL, 'any', 'contains', 'rekening', 'Transactions', TRUE, 215),
    (NULL, 'any', 'contains', 'langganan premium', 'Transactions', TRUE, 210),

    (NULL, 'sender_domain', 'contains', 'hire.lever.co', 'Job', TRUE, 245),
    (NULL, 'sender_domain', 'contains', 'greenhouse-mail.io', 'Job', TRUE, 245),
    (NULL, 'sender_domain', 'contains', 'ats.rippling.com', 'Job', TRUE, 245),
    (NULL, 'sender_domain', 'contains', 'teamtailor-mail.com', 'Job', TRUE, 245),
    (NULL, 'sender_domain', 'contains', 'workablemail.com', 'Job', TRUE, 245),
    (NULL, 'sender_domain', 'contains', 'hi.wellfound.com', 'Job', TRUE, 245),
    (NULL, 'sender_domain', 'contains', 'codility.com', 'Job', TRUE, 245),
    (NULL, 'sender_domain', 'contains', 'm.weworkremotely.com', 'Job', TRUE, 230),
    (NULL, 'sender_domain', 'contains', 'underdog.io', 'Job', TRUE, 230),
    (NULL, 'sender_domain', 'contains', 'micro1.ai', 'Job', TRUE, 230),
    (NULL, 'any', 'contains', 'successfully submitted', 'Job', TRUE, 210),
    (NULL, 'any', 'contains', 'codility assessment', 'Job', TRUE, 210),
    (NULL, 'any', 'contains', 'invites you to complete', 'Job', TRUE, 205),
    (NULL, 'any', 'contains', 'thank you for your application', 'Job', TRUE, 205),
    (NULL, 'any', 'contains', 'open to work', 'Job', TRUE, 170),

    (NULL, 'sender_domain', 'contains', 'habr.com', 'Social', TRUE, 220),
    (NULL, 'sender_domain', 'contains', 'discord.com', 'Social', TRUE, 170),
    (NULL, 'any', 'contains', 'mentioned you', 'Social', TRUE, 210),
    (NULL, 'any', 'contains', 'упомянул', 'Social', TRUE, 210),
    (NULL, 'any', 'contains', 'popular in your network', 'Social', TRUE, 180),
    (NULL, 'any', 'contains', 'самое интересное по вашим хабам', 'Social', TRUE, 180),

    (NULL, 'sender_domain', 'contains', 'marketing.go-jek.com', 'Promo', TRUE, 190),
    (NULL, 'sender_domain', 'contains', 'news.ozon.ru', 'Promo', TRUE, 180),
    (NULL, 'sender_domain', 'contains', 'newsletter.trip.com', 'Promo', TRUE, 180),
    (NULL, 'sender_domain', 'contains', 'info.sportmaster.ru', 'Promo', TRUE, 180),
    (NULL, 'sender_domain', 'contains', 'educative.io', 'Promo', TRUE, 160),
    (NULL, 'sender_domain', 'contains', 'artlist.io', 'Promo', TRUE, 160),
    (NULL, 'any', 'contains', 'travel radar', 'Promo', TRUE, 160),
    (NULL, 'any', 'contains', 'travel trends', 'Promo', TRUE, 160)
ON CONFLICT DO NOTHING;
