DELETE FROM user_rules
WHERE user_id IS NULL
  AND (rule_type, operator, rule_value, target_label, priority) IN (
    ('sender_domain', 'contains', 'steampowered.com', 'Security', 280),
    ('sender_domain', 'contains', 'nvidia.com', 'Security', 270),
    ('sender_domain', 'contains', 'id.apple.com', 'Security', 270),
    ('sender_domain', 'contains', 'hetzner.com', 'Security', 260),
    ('any', 'contains', 'security code', 'Security', 260),
    ('any', 'contains', 'new sign in', 'Security', 250),
    ('any', 'contains', 'new sign-in', 'Security', 250),
    ('any', 'contains', 'login link', 'Security', 250),
    ('any', 'contains', 'authenticator recovery', 'Security', 250),
    ('any', 'contains', 'account information updated', 'Security', 245),
    ('any', 'contains', 'access details', 'Security', 240),
    ('any', 'contains', 'authentication to your account', 'Security', 240),

    ('sender_domain', 'contains', 'permatabank.co.id', 'Transactions', 250),
    ('sender_domain', 'contains', 'customers.go-pay.co.id', 'Transactions', 245),
    ('any', 'contains', 'incoming transfer', 'Transactions', 230),
    ('any', 'contains', 'top up', 'Transactions', 220),
    ('any', 'contains', 'e-statement', 'Transactions', 220),
    ('any', 'contains', 'rekening', 'Transactions', 215),
    ('any', 'contains', 'langganan premium', 'Transactions', 210),

    ('sender_domain', 'contains', 'hire.lever.co', 'Job', 245),
    ('sender_domain', 'contains', 'greenhouse-mail.io', 'Job', 245),
    ('sender_domain', 'contains', 'ats.rippling.com', 'Job', 245),
    ('sender_domain', 'contains', 'teamtailor-mail.com', 'Job', 245),
    ('sender_domain', 'contains', 'workablemail.com', 'Job', 245),
    ('sender_domain', 'contains', 'hi.wellfound.com', 'Job', 245),
    ('sender_domain', 'contains', 'codility.com', 'Job', 245),
    ('sender_domain', 'contains', 'm.weworkremotely.com', 'Job', 230),
    ('sender_domain', 'contains', 'underdog.io', 'Job', 230),
    ('sender_domain', 'contains', 'micro1.ai', 'Job', 230),
    ('any', 'contains', 'successfully submitted', 'Job', 210),
    ('any', 'contains', 'codility assessment', 'Job', 210),
    ('any', 'contains', 'invites you to complete', 'Job', 205),
    ('any', 'contains', 'thank you for your application', 'Job', 205),
    ('any', 'contains', 'open to work', 'Job', 170),

    ('sender_domain', 'contains', 'habr.com', 'Social', 220),
    ('sender_domain', 'contains', 'discord.com', 'Social', 170),
    ('any', 'contains', 'mentioned you', 'Social', 210),
    ('any', 'contains', 'упомянул', 'Social', 210),
    ('any', 'contains', 'popular in your network', 'Social', 180),
    ('any', 'contains', 'самое интересное по вашим хабам', 'Social', 180),

    ('sender_domain', 'contains', 'marketing.go-jek.com', 'Promo', 190),
    ('sender_domain', 'contains', 'news.ozon.ru', 'Promo', 180),
    ('sender_domain', 'contains', 'newsletter.trip.com', 'Promo', 180),
    ('sender_domain', 'contains', 'info.sportmaster.ru', 'Promo', 180),
    ('sender_domain', 'contains', 'educative.io', 'Promo', 160),
    ('sender_domain', 'contains', 'artlist.io', 'Promo', 160),
    ('any', 'contains', 'travel radar', 'Promo', 160),
    ('any', 'contains', 'travel trends', 'Promo', 160)
  );
